# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KMS - powerful Ruby on Rails CMS for developers
email: info@webgradus.com
description: > # this means to ignore newlines until "baseurl:"
  KMS is a modern and flexible Ruby on Rails content management system with modular approach.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://getkms.com" # the base hostname & protocol for your site
docs_url: "http://docs.getkms.com"
twitter_username: webgradus
github_username:  webgradus

# Build settings
markdown: kramdown
